### PR TITLE
Changed EclSum import.

### PR DESCRIPTION
**Pull request by joakim-hove**
Using the old - but "protected" `ert.ecl` python package,

### CODE REVIEW

**Review by pgdr — DISMISSED** [review]
I obviously disagree with introducing a legacy requirement here.  That seems completely backwards, and I don't understand what you mean by `"protected"`.

However, if this will be merged anyway, I would strongly prefer a `try: import ; except import` pattern.

**Comment by joakim-hove** [comment]
> and I don't understand what you mean by "protected".

With that I mean that we have installed - through the `-DINSTALL_ERT_LEGACY` switch shims which redirect from `ert.ecl.xxx` to the correct location post https://github.com/Statoil/libecl/pull/298 - we have no such shims for `from ecl.ecl.xxx`

**Comment by joakim-hove** [comment]
> I would strongly prefer a try: import ; except import pattern.

I agree - will update.

**Comment by joakim-hove** [comment]
OK - I have changed the import statements to use `try: except ImportError`. 

Will first try using the `v0.0.2` version of `nex` - if that works as intended this whole PR becomes slightly irrelevant.

**Comment by JensGM** [comment]
Ser litt mer på denne i morgen, kan hende den blir assimilert inn i PRen for historiske data.

**Review by ReedOnly — APPROVED** [review]

**Pull request merged**
